# Generated by Django 3.2.4 on 2021-06-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
